apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind
  namespace: metallb-system
spec:
  addresses:
  - 172.20.255.200-172.20.255.250    

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kind
  namespace: metallb-system
spec:
  ipAddressPools:
  -  kind
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: kind-control-plane
  - matchLabels:
      kubernetes.io/hostname: kind-worker
