apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka-producer-client
    user-test-app: kafka-clients
  name: kafka-producer-client
  namespace: kafka
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: kafka-producer-client
        job-name: kafka-producer-client
        user-test-app: kafka-clients
      name: kafka-producer-client
      namespace: my-project
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: dev-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: TOPIC
              value: testBusData
            - name: MESSAGE_COUNT
              value: "100"
            - name: MESSAGE
              value: Hello-world
            - name: PRODUCER_ACKS
              value: all
            - name: LOG_LEVEL
              value: INFO
            - name: CLIENT_TYPE
              value: KafkaProducer
          image: quay.io/strimzi-test-clients/test-clients:latest-kafka-3.7.1
          imagePullPolicy: IfNotPresent
          name: kafka-producer-client
      restartPolicy: "Never"
    